# Generated by Django 5.2.4 on 2025-10-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Entreprise"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="Demande de contact",
                        max_length=200,
                        verbose_name="Sujet",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
            ],
            options={
                "verbose_name": "Demande de contact",
                "verbose_name_plural": "Demandes de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Poste")),
                (
                    "company",
                    models.CharField(
                        max_length=200, verbose_name="Entreprise/Organisation"
                    ),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("WORK", "Expérience professionnelle"),
                            ("RESEARCH", "Recherche"),
                            ("ACADEMIC", "Académique"),
                            ("VOLUNTEER", "Bénévolat"),
                        ],
                        max_length=10,
                        verbose_name="Type d'expérience",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                ("current", models.BooleanField(default=False, verbose_name="Actuel")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Technologies utilisées",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Expérience",
                "verbose_name_plural": "Expériences",
                "ordering": ["-start_date", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("ODOO", "Développement Odoo"),
                            ("IA", "Recherche IA"),
                            ("FULL", "Projet Full-Stack"),
                            ("ACADEMIC", "Projet Académique"),
                        ],
                        max_length=10,
                        verbose_name="Type de projet",
                    ),
                ),
                ("challenge", models.TextField(verbose_name="Défi/Contexte")),
                ("solution", models.TextField(verbose_name="Solution technique")),
                ("result", models.TextField(verbose_name="Résultats/Impact")),
                (
                    "technologies",
                    models.CharField(max_length=300, verbose_name="Stack technique"),
                ),
                (
                    "odoo_modules",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Modules Odoo"
                    ),
                ),
                (
                    "ai_techniques",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Techniques IA"
                    ),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="Lien GitHub")),
                (
                    "live_url",
                    models.URLField(blank=True, verbose_name="Lien vers le projet"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="projects/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                ("authors", models.CharField(max_length=400, verbose_name="Auteurs")),
                (
                    "conference",
                    models.CharField(max_length=200, verbose_name="Conférence/Journal"),
                ),
                ("year", models.IntegerField(verbose_name="Année")),
                (
                    "paper_url",
                    models.URLField(blank=True, verbose_name="Lien vers le papier"),
                ),
                (
                    "code_url",
                    models.URLField(blank=True, verbose_name="Lien vers le code"),
                ),
                ("abstract", models.TextField(blank=True, verbose_name="Résumé")),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Catégorie de compétence",
                "verbose_name_plural": "Catégories de compétences",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Débutant"),
                            ("INTERMEDIATE", "Intermédiaire"),
                            ("ADVANCED", "Avancé"),
                            ("EXPERT", "Expert"),
                        ],
                        max_length=15,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        verbose_name="Années d'expérience",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.skillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
                "ordering": ["category__display_order", "name"],
            },
        ),
    ]
