# Generated by Django 5.2.4 on 2025-10-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "professional_summary",
                    models.TextField(verbose_name="Résumé professionnel"),
                ),
                ("education", models.TextField(verbose_name="Formation")),
                ("volunteer_work", models.TextField(verbose_name="Bénévolat")),
                (
                    "personal_qualities",
                    models.TextField(verbose_name="Qualités personnelles"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contenu About",
                "verbose_name_plural": "Contenus About",
                "unique_together": {("language",)},
            },
        ),
    ]
