# Generated by Django 5.2.4 on 2025-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_aboutcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="CV", max_length=100, verbose_name="Titre du CV"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(upload_to="cv/", verbose_name="Fichier PDF"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fichier CV",
                "verbose_name_plural": "Fichiers CV",
                "unique_together": {("language",)},
            },
        ),
    ]
